server:
  port: 80

spring:
  application:
    name: cloud-consumer-consul-service
  cloud:
    consul:
      host: 192.168.65.192
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}