server:
  port: 8802

spring:
  application:
    name: cloud-stream-rabbitmq-consumer-service
  cloud:
    stream:
      binders:  #配置绑定信息
        defaultRabbit:  #名称 自定义
          type: rabbit   # 消息组件rabbit  和kafaka
          environment:   #消息队列环境变量配置
            spring:
              rabbitmq:
                host: 192.168.65.192
                port: 5672
                username: guest
                password: guest
      bindings:    #服务的整合
        input:    #通道的名称
          destination: cloudTestExchange  #使用的exchange
          contentType: application/json   #消息类型
          binder: defaultRabbit      #需要绑定的消息名称 上面定义的
          group: testGroup      #定义队列名 订阅同一个队列 防止重复消费，没有定义的话 随机生成一个队列绑定exchange 应用停止自动删除 AD


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: stream8802
    #访问路径可以显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    #lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    #lease-expiration-duration-in-seconds: 2