server:
  port: 9527


spring:
  application:
    name: cloud-gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true    #开启注册中心  通过服务名访问地址
      routes:
        - id: payment_route      #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-HYSTRIX-SERVICE   #lb代表使用loadbalance  负载均衡
          predicates:
            - Path=/payment/get/**  #断言，路径匹配的进行路由 有多种断言匹配 After、Before、Between  时间在这之间访问正常
                                    #Cookie name,pattern  cookie匹配正则 放行
                                    #Header name,pattern  header匹配正则  放行 同理 Host=*.zz.com
                                    #Method  请求方法   Path 请求路径  Query  查询参数是什么放行
        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-HYSTRIX-SERVICE
          predicates:
            - Path=/payment/lb/**

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway9527
    #访问路径可以显示IP地址
    prefer-ip-address: true